# taps
tap "homebrew/bundle"
tap "oven-sh/bun"
tap "stripe/stripe-cli"
tap "stripe/stripe-mock"

# cli essentials
brew "awscli"
brew "bash"
brew "bat"
brew "btop"
brew "cloudflared"
brew "coreutils"
brew "curl"
brew "direnv"
brew "dust"
brew "eza"
brew "fd"
brew "ffmpeg"
brew "fzf"
brew "gh"
brew "git"
brew "git-delta"
brew "git-extras"
brew "git-filter-repo"
brew "gnu-sed"
brew "gnupg"
brew "grep"
brew "jq"
brew "lazygit"
brew "mas"
brew "mise"
brew "mkcert"
brew "node"
brew "php"
brew "pipx"
brew "postgresql@17"
brew "redis"
brew "ripgrep"
brew "sheldon"
brew "starship"
brew "stow"
brew "tmux"
brew "topgrade"
brew "tree"
brew "watch"
brew "wget"
brew "yazi"
brew "yq"
brew "yt-dlp"
brew "zoxide"
brew "oven-sh/bun/bun"
brew "stripe/stripe-cli/stripe"
brew "stripe/stripe-mock/stripe-mock"

# media / image
brew "webp"
brew "imagemagick"
brew "gifsicle"
brew "jpegoptim"
brew "oxipng"
brew "pngpaste"
brew "pngquant"

# python
brew "python@3.14"
brew "python-tk@3.14"

# fonts
cask "font-fira-code-nerd-font"
cask "font-jetbrains-mono-nerd-font"

# core apps
cask "1password"
cask "1password-cli"
cask "adguard"
cask "appcleaner"
cask "chatgpt"
cask "ghostty"
cask "iina"
cask "keka"
cask "raycast"
cask "rectangle-pro"
cask "shottr"
cask "textsniper"
cask "yoink"
cask "zed"
