cask_args appdir: '/Applications'

tap 'homebrew/bundle'

brew 'atuin'
brew 'cloudflared'
brew 'imagemagick'
brew 'postgresql@17'
brew 'redis'
brew 'ruby-build'
brew 'spaceman-diff'
brew 'spark'
brew 'stripe/stripe-cli/stripe'
brew 'stripe/stripe-mock/stripe-mock'
brew 'wget'
brew 'yt-dlp'

cask '1password'
cask 'ghostty'
cask 'handbrake-app'
cask 'steam'
cask 'transmission'